services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "${HOST_BACKEND_PORT}:${APP_PORT}"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${HOST_FRONTEND_PORT}:${NGINX_FRONTEND_PORT}"
